;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;;   Kernel16.inc (c) Ville Turjanmaa
;;   License: GPL. See file copying for details.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   
;% +include
   
include "BOOTENG.INC"     ; english system boot messages
include "BOOTCODE.INC"    ; 16 bit system boot code
   
include "PCI16.INC"

;% -include
   
   
   
