
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                          ;;
;;   WINDOW SKIN for MenuetOS               ;;
;;                                          ;;
;;   entryway@bkg.lt                        ;;
;;                                          ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



_skinh          dd      22

_refleft        dd      0
_skinleft       dd      0
_skinleftw      dd      66

_refbase        dd      0
_skinbase       dd      66
_skinbasew      dd      10

_refoper        dd      0
_skinoper       dd      -58
_skinoperw      dd      58

_buttonCx       dd      5  
_buttonCy       dd      5   
_buttonCw       dd      11   
_buttonCh       dd      11   

_buttonMx       dd      24
_buttonMy       dd      2
_buttonMw       dd      17
_buttonMh       dd      18

_buttonPx       dd      41
_buttonPy       dd      2
_buttonPw       dd      17
_buttonPh       dd      18


defbuttoncolor    dd   0x465670  ; 364660 ; 365260
defbuttoncolor2   dd   0xc8c8c8  ; c0c0c0 

_colorframe     dd      0x33465f ; 23364F ; 00365260
_colorborder    dd      0x0
_coloroutborder dd      0x0

_fileleft       db      'LEFT.RAW     '
_filebase       db      'BASE.RAW     '
_fileoper       db      'OPER.RAW     '

_skinwinw       dd      0

;

v_skinh          dd      38

v_skinleft       dd      0
v_skinleftw      dd      66

v_skinbase       dd      66
v_skinbasew      dd      10

v_skinoper       dd      -58
v_skinoperw      dd      58



